### ISSUE TITLE
resource not found

### ISSUE THREAD

**Issue by sakebook** [sakebook/Zipangu#1]
json file is not found. in version 0.1.0

```
java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: org.json.JSONException: No value for code
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
                                                                     at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                  Caused by: org.json.JSONException: No value for code
                                                                     at org.json.JSONObject.get(JSONObject.java:389)
                                                                     at org.json.JSONObject.getInt(JSONObject.java:478)
                                                                     at com.sakebook.android.library.zipangu.Zipangu.beginning(Zipangu.kt:42)
                                                                     at com.sakebook.android.library.zipangu.Zipangu.beginning(Zipangu.kt:25)
```

**Comment by kong112** [comment]
5.0.2

**Comment by kong112** [comment]
V9.0.42

**Comment by kong112** [comment]
at com.sakebook.android.library.zipangu.Zipangu.beginning(Zipangu.kt:42)

**Comment by kong112** [comment]
0010000100001
